const db = {
    and : {nepali : 'र'},
    the : {nepali : 'को'},
    that : {nepali : 'त्यो'},
    then : {nepali : 'त्यसो भए'},
    this : {nepali : 'यो'},
    I : {nepali : 'म'},
    or : {nepli : 'वा'},
    from : {nepali : 'बाट'},
    where : {nepali : 'कहाँ'},
    what : {nepali : 'के'},
    why : {nepali : 'किन'},
    when : {nepali : 'कहिले'},
    for : {nepali : 'को लागी'},
    are : {nepali : 'छन्'},
    how : {nepali : 'कसरी'},
    is : {nepali : 'छ'},
    name : {nepali : 'नाम'},
    water : {nepali : 'पानी'},
    pen : {nepali : 'कलम'},
    paper : {nepali : 'कागज'},
    book : {nepali : 'किताव'},
    food : {nepali : 'खाना'},
    clock : {nepali : 'घडी'},
    plate : {nepali : 'प्लेट'},
    bowl : {nepali : 'कचौरा'},
    table : {nepali : 'टेबल'},
    chair : {nepali : 'कुर्सी'},
    spoon : {nepali : 'चम्चा'},
    fork : {nepali : 'काँटा'},
    knife : {nepali : 'चक्कु'},
    stairs : {nepali : 'सिढी'},
    cook : {nepali : 'कुक'},
    write : {nepali : 'लेख्नुहोस्'},
    hello : {nepali : 'नमस्कार'},
    door : {nepali : 'ढोका'},
    window : {nepali : 'विन्डो'},
    sleep : {nepali : 'सुत्नु'},
    walk : {nepali : 'हिंड'},
    run : {nepali : 'चलाउनुहोस्'},
    sit : {nepali : 'बस्नुहोस्'},
    stand : {nepali : 'खडा'},
    respect : {nepali : 'आदर'},
    thankyou : {nepali : 'धन्यवाद'},
    please : {nepali : 'कृपया'},
    yes : {nepali : 'हो'},
    no : {nepali : 'होईन'},
    okay : {nepali : 'ल'},
    
}

export default db;